language: c++

matrix:
    include:
        - os: linux
        - os: osx

before_install:
    - if [ $TRAVIS_OS_NAME = osx ]; then rvm get head; fi

script:
    - make
    - fname=$(echo "soulsum_$(uname)_$(uname -m)" | tr '[:upper:]' '[:lower:]' | tr -dc 'a-z0-9._')
    - tar -zcvf "${fname}.tar.gz" soulsum
    - echo "Deploy ${fname}.tar.gz"

deploy:
    provider: releases
    api_key:
        secure: $GITHUB_AUTH
    file_glob: true
    file: soulsum_*.tar.gz
    overwrite: true
    skip_cleanup: true
    #    on:
    #        tags: true
