language: c++

matrix:
    include:
        - os: linux
        - os: osx

before_install:
    - rvm get stable --auto-dotfiles

script:
    - make
    - fname=$(echo "soulsum_$(uname)_$(uname -m)" | sed 's/./\l&/g' | tr -dc 'a-z0-9._')
    - tar -zcvf "${fname}.tar.gz" soulsum

deploy:
    provider: releases
    api_key:
        secure: $GITHUB_AUTH
    file_glob: true
    file: soulsum_*.tar.gz
    overwrite: true
    skip_cleanup: true
    on:
        tags: true
